#!/bin/sh
set -ex

# Build conn-check in a "builder" image.
docker build --rm \
  --build-arg VERSION=${VERSION} \
  -t conn-check-builder builder/

# Copy wheels.tgz, which contains the built files.
script/clean
docker create --name ccv conn-check-builder true
docker cp ccv:/home/user/conn-check/wheels.tgz runtime/

# Build a runtime image.
docker build --rm \
  --build-arg BUILD_DATE=${BUILD_DATE} \
  --build-arg VCS_REF=${VCS_REF} \
  --build-arg VERSION=${VERSION} \
  -t conn-check runtime/

# Show image sizes.
docker images | grep conn-check
