#!/bin/sh
set -ex

cat > ci/vars <<EOF
export VERSION=1.3.1
export BUILD_DATE=$(date +%Y%m%dT%H%M)
export VCS_REF=$(git rev-parse --short HEAD)
export TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF
. ci/vars

# Build conn-check in a "builder" image.
docker build --rm \
  --build-arg VERSION=${VERSION} \
  -t conn-check-builder builder/

# Copy wheels.tgz, which contains the built files.
ci/clean
docker create --name ccv conn-check-builder true
docker cp ccv:/home/user/conn-check/wheels.tgz runtime/

# Build a runtime image.
docker build --rm \
  --build-arg BUILD_DATE=${BUILD_DATE} \
  --build-arg VCS_REF=${VCS_REF} \
  --build-arg VERSION=${VERSION} \
  -t conn-check runtime/

# Show image sizes.
docker images | grep conn-check
