#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Build image(s). Invoke as "ci/build".
################################################################################

cat > ci/vars <<EOF
declare -rx VERSION=1.3.1
declare -rx BUILD_DATE=$(date +%Y%m%dT%H%M)
declare -rx VCS_REF=$(git rev-parse --short HEAD)
declare -rx TAG=\${VERSION}-\${BUILD_DATE}-git-\${VCS_REF}
EOF
. ci/vars
. ci/functions.sh

echo
echo Build conn-check in a \"builder\" image.
docker build --rm \
  --build-arg VERSION="${VERSION}" \
  -t conn-check-builder builder/

echo
echo Copy wheels.tgz, which contains the built files.
ci/clean
docker create --name ccv conn-check-builder true
docker cp ccv:/home/user/conn-check/wheels.tgz runtime/

echo
echo Build a runtime image.
docker build --rm \
  --build-arg BUILD_DATE="${BUILD_DATE}" \
  --build-arg VCS_REF="${VCS_REF}" \
  --build-arg VERSION="${VERSION}" \
  -t conn-check runtime/

echo
echo Show image sizes.
docker images | grep conn-check
