#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Clean the local build environment. Invoke as "ci/clean".
################################################################################

. ci/functions.sh

docker rm -f ccv || :
docker volume ls -qf dangling=true | xargs docker volume rm || :
docker images -qf dangling=true | xargs docker rmi || :

rm -f runtime/wheels.tgz || :
