#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/vars
. ci/functions.sh

echo
echo Check for things like whitespace, shell syntax, and binary files.
ci/check-files -d

echo
echo Run BATS tests.
bats test/*.bats
