#!/bin/bash
set -e
set -u
set -o pipefail

################################################################################
# Run the test harness. Invoke as "ci/test".
################################################################################

. ci/vars
. ci/bootstrap
. ci/functions.sh

echo
echo Check for things like whitespace, shell syntax, and binary files.
pre-commit run --all-files --verbose --hook-stage manual

echo
echo Run BATS tests.
bats ci/*.bats
